service: Assignment3-SMS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  timeout: 15

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  # - serverless-apigw-binary
  - serverless-static 

# custom:
#   apigwBinary:
#     types:
#       - '*/*' # Allow all binary types (images, CSS, etc.)
custom:
  static:
    path: ./public # select the folder you want to serve
    port: 3000 # select a specific port 


# package:
#   individually: true # Package each function individually to avoid size limits
