service: Assignment3-SMS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  timeout: 15

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline



